# New ports collection makefile for:    bkpupsd
# Version required:     2.0
# Date created:         30 August 2000
# Whom:                 taca
#
# $Id: Makefile,v 1.2 2002/12/21 17:44:04 taca Exp $
#

DISTNAME=	bkpupsd-2.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.jepro.co.jp/pub/jepro/misc

MAINTAINER=	taca@back-street.net

MAN5=		upstab.5
MAN8=		bkpupsd.8

.include <bsd.port.mk>
