# New ports collection makefile for:    bkpupsd
# Version required:     2.0
# Date created:         30 August 2000
# Whom:                 taca
#
# $Id: Makefile,v 1.2 2002/12/21 17:44:04 taca Exp $
#

PORTNAME= bkpupsd
PORTVERSION= 2.0pl3
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.jepro.co.jp/pub/jepro/misc/
DISTNAME= ${PORTNAME}-${PORTVERSION}

MAINTAINER=	taca@back-street.net

.include <bsd.port.mk>
